<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Alacrity.PluginSdk\Alacrity.PluginSdk.csproj" />
    <ProjectReference Include="..\Alacrity.Core\Alacrity.Core.csproj" />
    <ProjectReference Include="..\Alacrity.App\Alacrity.App.csproj" />
    <ProjectReference Include="..\Alacrity.UiTestPlugin\Alacrity.UiTestPlugin.csproj" />
    <ProjectReference Include="..\Alacrity.BetterChat\Alacrity.BetterChat.csproj" />
    <ProjectReference Include="..\Alacrity.PlayerList\Alacrity.PlayerList.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Alacrity.TerrariaIntegration\BridgeReflectionContracts.cs" Link="BridgeReflectionContracts.cs" />
    <Compile Include="..\Alacrity.TerrariaIntegration\TileStorage.cs" Link="TileStorage.cs" />
  </ItemGroup>
</Project>
