<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Alacrity.PluginSdk\Alacrity.PluginSdk.csproj" />
    <ProjectReference Include="..\Alacrity.Core\Alacrity.Core.csproj" />
    <ProjectReference Include="..\Alacrity.App\Alacrity.App.csproj" />
  </ItemGroup>
</Project>
