<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>AlacrityBootstrapRuntime</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AlacrityBootstrapRuntime.cs" />
  </ItemGroup>
</Project>
