using System;

namespace Alacrity.PluginSdk;

/// <summary>Host compatibility versions shared by packaged plugins and the patched bridge.</summary>
public static class AlacrityCompatibility
{
    /// <summary>Current public SDK contract level.</summary>
    // ITerrariaServices gained RenderingOptimizations. Adding an interface member is a binary
    // break for third-party implementations, so it intentionally starts SDK compatibility v3.
    public const int PluginSdk = 3;
    /// <summary>Current Core host contract level.</summary>
    public const int Host = 2;
    /// <summary>Current static Terraria bridge ABI level.</summary>
    public const int BridgeAbi = 3;
}

/// <summary>Immutable package requirements checked before a plugin assembly is loaded.</summary>
public sealed class PluginCompatibilityRequirements
{
    /// <summary>Creates exact compatibility requirements for the package.</summary>
    public PluginCompatibilityRequirements(int pluginSdkVersion, int hostVersion, int bridgeAbiVersion)
    {
        if (pluginSdkVersion <= 0) throw new ArgumentOutOfRangeException(nameof(pluginSdkVersion));
        if (hostVersion <= 0) throw new ArgumentOutOfRangeException(nameof(hostVersion));
        if (bridgeAbiVersion <= 0) throw new ArgumentOutOfRangeException(nameof(bridgeAbiVersion));
        PluginSdkVersion = pluginSdkVersion;
        HostVersion = hostVersion;
        BridgeAbiVersion = bridgeAbiVersion;
    }

    /// <summary>Requirements for manifests produced before explicit compatibility metadata existed.</summary>
    public static PluginCompatibilityRequirements Legacy { get; } = new PluginCompatibilityRequirements(1, 1, 1);
    /// <summary>Requirements generated by the current SDK packaging path.</summary>
    public static PluginCompatibilityRequirements Current { get; } = new PluginCompatibilityRequirements(AlacrityCompatibility.PluginSdk, AlacrityCompatibility.Host, AlacrityCompatibility.BridgeAbi);
    /// <summary>Required public PluginSdk contract level.</summary>
    public int PluginSdkVersion { get; }
    /// <summary>Required Core host contract level.</summary>
    public int HostVersion { get; }
    /// <summary>Required patch-facing Terraria bridge ABI level.</summary>
    public int BridgeAbiVersion { get; }
}
