// <auto-generated />
// Generated by tools/StaticTileChunkAudit against Terraria 1.4.5.6.
// Do not edit by hand. Regenerate after changing the audit rules or Terraria version.
namespace AlacrityTerraria.Rendering.TileChunks;

internal static class StaticTileChunkEligibility
{
    private static readonly ulong[] EligibleTypeWords =
    {
        0x1A001AE040800006UL,
        0x01C0200000001840UL,
        0x50FB8000FFD01000UL,
        0x3700002600014DCEUL,
        0x0880000000060000UL,
        0x80020020020002C6UL,
        0x0000000783000002UL,
        0x18F51000E7000400UL,
        0x000C00000000001FUL,
        0x0800000000000000UL,
        0x000018FFE4600002UL,
        0x00002FF7C0040000UL,
    };

    internal static bool IsEligible(ushort type)
    {
        int wordIndex = type >> 6;
        return wordIndex < EligibleTypeWords.Length &&
            (EligibleTypeWords[wordIndex] & (1UL << (type & 63))) != 0;
    }
}
